name: $(Build.DefinitionName)-$(Build.SourceBranchName)-$(date:yyyyMMdd)$(rev:.r)
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
parameters:
- name: stgDeploy
  type: boolean
  default: true
  displayName: "Deploy to Staging"  

- name: prodDeploy
  type: boolean
  default: false
  displayName: "Deploy to Prod" 

 
stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
        script: |
          pip install -r requirements.txt
    - task: Bash@3
      displayName: 'Create Deploy Package'
      inputs:
          targetType: 'inline'
          script: |
            sudo apt-get install zip unzip -qy
            zip -r $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip .
    - task: PublishBuildArtifacts@1
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          artifactName: main
      displayName: 'Publish  artifact'

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to stage
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
       buildType: 'current'
       downloadType: 'single'
       artifactName: 'main'
       downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azureSubscription)
        appType: 'webAppLinux'
        WebAppName: 'hello-stg'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
        RuntimeStack: 'PYTHON|3.8'
    
    - task: AzureWebApp@1
      condition: succeeded()
      displayName: Deploy to production
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azureSubscription)
        appType: 'webAppLinux'
        WebAppName: 'hello-prd'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
        RuntimeStack: 'PYTHON|3.8'
        
